trigger:
  branches:
    include:
    - refs/heads/main
  paths:
    include:
    - AzureRM/*
  batch: True
jobs:
- job: Job_1
  displayName: Publish Artifact
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
  - task: UniversalPackages@0
    displayName: Universal publish to Azure Artifacts Gallery
    inputs:
      command: publish
      publishDirectory: AzureRM
      feedListPublish: ef857dd4-4818-49a2-b4d4-e1001e9c25a9
      packageListPublish: core_terraform_modules
      packagePublishDescription: This package contains the Terraform modules and the code calling the corresponding TF module. Require TFVars file to execute
...
